// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"clean-architecture-practice/internal/infrastructure/repository"
	"clean-architecture-practice/internal/interfaces/handler"
	"clean-architecture-practice/internal/usecase"
)

// Injectors from wire.go:

func Wire() (*handler.UserHandler, error) {
	userRepository := repository.NewUserMemoryRepository()
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler, nil
}
